### ISSUE TITLE
Bug in target setting

### ISSUE THREAD

**Issue by Supreethsharma** [rakshith4able/Personal-Web-Projects#1]
Bug: The Count goes on incrementing for both players if the target is set to 0

**Comment by rakshith4able** [comment]
> Bug: The Count goes on incrementing for both players if the target is set to 0

Yeah! Supreeth You are right. I saw the issue when the target is set to zero. Thank You and I'm terribly sorry this has happened. I have fixed it! Below is the updated code snippet.


//Updated Code
function updateScores(player, opponent) {
    if (!isGameOver) {
        if (winningScore === 0) {
            alert("Please enter target Greater than 0");
        }
        else {
            player.score += 1;
            if (player.score === winningScore) {
                isGameOver = true;
                player.display.classList.add('win');
                opponent.display.classList.add('lose');
                player.button.disabled = true;
                opponent.button.disabled = true;
            }
            player.display.textContent = player.score;
        }
    }
}
